# Generated by Django 5.2.17 on 2026-09-09 11:53

from django.db import migrations


def copy_data_forward(apps, schema_editor):
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    NewProfile = apps.get_model("profiles", "Profile")

    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            pk=old_profile.pk,
            user_id=old_profile.user_id,
            favorite_city=old_profile.favorite_city,
        )


def copy_data_backward(apps, schema_editor):
    apps.get_model("profiles", "Profile").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_data_forward, copy_data_backward),
    ]
