# Generated by Django 5.2.17 on 2026-09-09 11:53

from django.db import migrations


def copy_data_forward(apps, schema_editor):
    OldAddress = apps.get_model("oc_lettings_site", "Address")
    NewAddress = apps.get_model("lettings", "Address")
    OldLetting = apps.get_model("oc_lettings_site", "Letting")
    NewLetting = apps.get_model("lettings", "Letting")

    for old_address in OldAddress.objects.all():
        NewAddress.objects.create(
            pk=old_address.pk,
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )

    for old_letting in OldLetting.objects.all():
        NewLetting.objects.create(
            pk=old_letting.pk,
            title=old_letting.title,
            address_id=old_letting.address_id,
        )


def copy_data_backward(apps, schema_editor):
    apps.get_model("lettings", "Letting").objects.all().delete()
    apps.get_model("lettings", "Address").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lettings", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_data_forward, copy_data_backward),
    ]
