# Generated by Django 5.2.17 on 2026-09-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0003_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
    ]
