# Generated by Django 5.2.17 on 2026-09-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
        ("lettings", "0002_copy_data_from_oc_lettings_site"),
        ("profiles", "0002_copy_data_from_oc_lettings_site"),
    ]

    operations = [
        migrations.DeleteModel(name="Letting"),
        migrations.DeleteModel(name="Address"),
        migrations.DeleteModel(name="Profile"),
    ]
